name: TestPostgres

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      database_connect:
        image: postgres:latest
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: 'trust'
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run the query in DB
        env:
          PGHOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: mkdir output

        
      - name: Run mode       
        env:
          PGHOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          psql -U postgres -d test_db -f ./mode.sql |  tee -a ./output/output.log

      - name: Run trevor       
        env:
          PGHOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          psql -U postgres -d test_db -f ./trevor.sql |  tee -a ./output/output1.log
      - name: Run learn       
        env:
          PGHOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          psql -U postgres -d test_db -f ./learn.sql |  tee -a ./output/output2.log           
          cd ./output/
          ls -l
      - name: Output File
        run: |
          ls -l
          cat ./output/output.log
          cat ./output/output1.log
          cat ./output/output2.log 
        
