name: 06 - Contexts

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: string
        default: new name overwritten

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
jobs:
 echo-data:
   runs-on: ubuntu-latest
     
   steps:
     - name: Display Information
       run: |
         sudo apt-get install jq
         echo -e '{"applicationId": "22AE",\n"category": "Service call failed for job"}'       
         echo "Event name: ${{github.event_name}}"
         echo "Ref: ${{github.ref}}"
         echo "SHA name: ${{github.sha}}"
         echo "Actor: ${{github.actor}}"
         echo "Workflow: ${{github.workflow}}"
         echo "Run ID: ${{github.run_id}}"
         echo "Run number: ${{github.run_number}}"
         expr 123456 + 7890
     - name: Retrieve Variable
       run: |
        payload=$(jq -n '{
          emptyArray: [],
          user: {
          name: "John Doe",
          address: {
            street: "123 Main St",
            city: "Springfield"
            },
          hobbies: ["reading", "cycling", "gaming"],
          projects: [
          {
            name: "Project Alpha",
            status: "completed"
          },
          {
            name: "Project Beta",
            status: "in progress"
           }
          ]
         }
        }')

        echo "$payload"
        
     - name: Print Env Variables
       env:
         MY_OVERWRITTEN_VAR: step
         MY_WORKFLOW_VAR: workslow
       run: |
        echo "[ 
        applicationId: "22",
        category: "Service call failed for ${env}",
        cogs: [],
        content: "scheduler service call failed for ${env}",
        emailData: [
            content: "Error failedAssignments: ${failedAssignments}",
            locale: "en_US",
            subject: "Service call failed."
        ],
        expiryDays: "100",
        groups: [],
        others: [
            key: "string"
        ],
        referenceUrl: "",
        users: ["no"]]" > file.json
        jq -r '.' file.json > file1.json
        cat file1.json
        
         
