name: 09 - Using Functions

on: 
  pull_request:
  workflow_dispatch:
  

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        id: failstep
        run: |
          exit 0
  echo2:
    runs-on: ubuntu-latest
    needs: echo1
    steps:
      - name: I will execute
        if: ${{ !cancelled() }}
        run: |
          echo "I will always print, except when the workflow is cancelled."
          echo "${{ needs.echo1.result }}"
  echo3:
    runs-on: ubuntu-latest
    needs: [echo1,echo2]
    steps:
      - name: I will execute when cancelled
        run: |
          echo "execite"
