name: 09 - Using Functions

on: 
  pull_request:
  workflow_dispatch:
  

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        id: failstep
        run: |
          exit 0

      - name: I will execute
        id: successstep
        if: ${{ !cancelled() }}
        run: |
          echo "I will always print, except when the workflow is cancelled."
          exit 1
          

      - name: I will execute when cancelled
        if: ${{ failure() && steps.failstep.conclusion == 'failure' || steps.successstep.conclusion == 'failure' }}
        run: |
          echo "execite"
