name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options: ['Success','Failure']
        default: Success
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.Build.outputs.status}}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo $GITHUB_OUTPUT
        
      - name: Build
        id: Build
        run: |
          echo "status=${{inputs.build-status}}" >> $$GITHUB_OUTPUT

          
          
            
