name: COntainerApp

on:
  workflow_dispatch

jobs:
  checkout:
    runs-on : ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: install node.js
        run: |
          mkdir container-express-app
          apt-get install jq
      - name: create dir
        run: |
          npm init -y
          ls
          cat package.json
      - name : install parser and express
        run: |
          npm install express@4.19.2 body-parser@1.20.2 --save-exact
          ls
          cat package.json
      - name: change json key
        run: |
          jq '.' package.json
          cd ./.github/workflows
          jq '.scripts.start' = "node index.js"
          cp ../../index.js ./container-express-app
          cd ../../container-express-app
          ls
          npm start
          curl http://localhost:3000
          

      
