name: COntainerApp

on:
  workflow_dispatch

jobs:
  checkout:
    runs-on : ubuntu-latest
    steps:
      - name: install node.js
        run: |
          mkdir container-express-app
          sudo apt-get install jq
      - name: create dir
        run: |
          cd container-express-app
          npm init -y
          ls
          cat package.json
      - name : install parser and express
        run: |
          npm install express@4.19.2 body-parser@1.20.2 --save-exact
          ls
          cat package.json
      - name: checkout Repo
        uses: actions/checkout@v4    
      - name: change json key
        run: |
          pwd
          ls -al
          jq '.scripts | keys' = "start" ../container-express-app/package.json
          jq '.scripts.start' = "node index.js" ../container-express-apppackage.json
          cp ./.github/workflows/index.js ./container-express-app
          cd container-express-app
          ls
          npm start
          curl http://localhost:3000
          

      
