name: 13-docker-setup

on: 
  workflow_dispatch


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: avialable docker ver
        run: |
          docker --version
          sudo docker run hello-world
