name: Docker setup from Docker file

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: install Docker
        uses: docker/setup-docker-action@v4
      - name: Docker login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.USR_DCK }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: search image nginx in docker
        run: |
          docker search  hello-world
          

      - name: docker create image from docker file
        run: |
          docker build -t julu:v1 ./.github/workflows/
          docker images
          docker tag  julu:v1 julu:v2
          docker images
          
        
     
